"""Hyperlinks: external URLs and internal jump-to-slide links.

Contract (all ops modules): every function takes the open PptxPackage first,
mutates only the in-memory package, calls pkg.mark_dirty() on every part it
touches, and returns a summary dict. Nothing here writes to disk.

Two link kinds, one writer:
- External: a:hlinkClick r:id -> a hyperlink-reltype rel with
  TargetMode="External" whose Target is the URL.
- Jump-to-slide: a:hlinkClick r:id + action="ppaction://hlinksldjump" -> an
  internal slide-reltype rel targeting the destination slide part. This is
  exactly the structure ops/slides.py's delete GC recognizes and neuters
  (rel dropped, hlinkClick removed) when the destination slide is deleted,
  so links written here stay consistent with slide CRUD.

Link placement: on a whole shape (a:hlinkClick as first child of the
shape's cNvPr) or on a text range (a:hlinkClick inside a:rPr of the covered
runs, splitting boundary runs; several runs may share one rel id, matching
PowerPoint's own output). Media playback affordances (hlinkClick with
action="ppaction://media" on video/audio frames) are never treated as
hyperlinks: the writer refuses to clobber them and the reader skips them.

Text-range offsets count characters in paragraph render order the same way
ops/read.py renders it: each a:r counts len(a:t), a:br counts 1, a:fld
counts its cached text. Ranges overlapping an a:fld refuse (a field's text
is regenerated by PowerPoint; splitting it is meaningless); an a:br inside
the range is skipped (a break cannot carry a link).
"""

from __future__ import annotations

import copy
import posixpath

from lxml import etree

from ..core.errors import (
    PptMcpError,
    TargetNotFound,
    UnsupportedStructure,
)
from ..core.package import (
    NSMAP,
    PptxPackage,
    RT_SLIDE,
    qn,
    rels_name,
    resolve_target,
)
from . import shapes as _shapes
from .read import iter_shapes, resolve_slide, slide_table, slides_in_scope

RT_HYPERLINK = (
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink"
)

_ACTION_SLIDE_JUMP = "ppaction://hlinksldjump"
_ACTION_MEDIA = "ppaction://media"
_ACTION_SHOW_JUMP = "ppaction://hlinkshowjump"

_R_ID = qn("r:id")


# ---------------------------------------------------------------- addressing


def _parse_target(target) -> dict:
    """Normalize the `target` selector: a shape id (int) links the whole
    shape; {"shape_id": N, "paragraph": P[, "start": S, "end": E]} links a
    text range (whole paragraph when start/end are omitted)."""
    if isinstance(target, bool):
        raise PptMcpError(f"invalid target {target!r}")
    if isinstance(target, int):
        return {"shape_id": target, "text": False}
    if isinstance(target, dict) and "shape_id" in target:
        known = {"shape_id", "paragraph", "start", "end"}
        unknown = set(target) - known
        if unknown:
            raise PptMcpError(
                f"unknown target key(s) {sorted(unknown)}; valid: "
                f"{sorted(known)}"
            )
        if "paragraph" not in target:
            if "start" in target or "end" in target:
                raise PptMcpError(
                    "start/end require a paragraph index in the target"
                )
            return {"shape_id": int(target["shape_id"]), "text": False}
        para = target["paragraph"]
        if not isinstance(para, int) or isinstance(para, bool) or para < 0:
            raise PptMcpError(
                f"paragraph must be a 0-based index, got {para!r}"
            )
        start = target.get("start")
        end = target.get("end")
        if (start is None) != (end is None):
            raise PptMcpError("pass both start and end, or neither")
        if start is not None:
            if not all(
                isinstance(v, int) and not isinstance(v, bool)
                for v in (start, end)
            ) or start < 0 or end <= start:
                raise PptMcpError(
                    f"start/end must be 0-based character offsets with "
                    f"start < end, got start={start!r} end={end!r}"
                )
        return {
            "shape_id": int(target["shape_id"]),
            "text": True,
            "paragraph": para,
            "start": start,
            "end": end,
        }
    raise PptMcpError(
        f"invalid target {target!r}: pass a shape id or "
        '{"shape_id": N, "paragraph": P, "start": S, "end": E}'
    )


def _cnvpr_of(elem: etree._Element) -> etree._Element:
    cnvpr = next(elem.iter(qn("p:cNvPr")), None)
    if cnvpr is None:
        raise UnsupportedStructure("shape has no cNvPr; refusing to guess")
    return cnvpr


def _paragraphs_of(elem: etree._Element) -> list[etree._Element]:
    body = elem.find(qn("p:txBody"))
    if body is None:
        raise UnsupportedStructure(
            "shape has no text body; a text-range hyperlink needs a shape "
            "with text (link the whole shape instead)"
        )
    return body.findall(qn("a:p"))


# ------------------------------------------------------------ run splitting


def _run_text(run: etree._Element) -> str:
    t = run.find(qn("a:t"))
    return t.text or "" if t is not None else ""


def _fld_len(fld: etree._Element) -> int:
    t = fld.find(qn("a:t"))
    return len(t.text or "") if t is not None else 0


def _paragraph_len(p_el: etree._Element) -> int:
    n = 0
    for child in p_el:
        tag = etree.QName(child).localname
        if tag == "r":
            n += len(_run_text(child))
        elif tag == "br":
            n += 1
        elif tag == "fld":
            n += _fld_len(child)
    return n


def _split_run(run: etree._Element, offset: int) -> etree._Element:
    """Split one a:r at a character offset; the ORIGINAL element keeps the
    tail and a deep copy carrying the head is inserted before it (both keep
    the run's rPr). Returns the original (tail) element."""
    t_el = run.find(qn("a:t"))
    text = t_el.text or ""
    head = copy.deepcopy(run)
    run.addprevious(head)
    head.find(qn("a:t")).text = text[:offset]
    t_el.text = text[offset:]
    return run


def _validate_range(p_el: etree._Element, start: int, end: int) -> None:
    """All range refusals, BEFORE any tree mutation: fld overlap, end past
    the paragraph, no covered run text."""
    pos = 0
    any_text = False
    for child in p_el:
        tag = etree.QName(child).localname
        if tag == "r":
            text = _run_text(child)
            r_start, r_end = pos, pos + len(text)
            pos = r_end
            if text and r_end > start and r_start < end:
                any_text = True
        elif tag == "br":
            pos += 1
        elif tag == "fld":
            f_start, f_end = pos, pos + _fld_len(child)
            pos = f_end
            if f_end > start and f_start < end:
                raise UnsupportedStructure(
                    "the text range overlaps a field (slide number/date); "
                    "fields regenerate their text, so linking across one is "
                    "refused. Narrow the range to plain text runs."
                )
    if end > pos:
        raise PptMcpError(
            f"range end {end} is past the paragraph's {pos} characters"
        )
    if not any_text:
        raise PptMcpError(
            f"range [{start}, {end}) covers no text runs in the paragraph"
        )


def _covered_runs(
    p_el: etree._Element, start: int, end: int
) -> list[etree._Element]:
    """The a:r elements exactly covering [start, end), splitting boundary
    runs in place. Call _validate_range first; this pass cannot fail."""
    covered: list[etree._Element] = []
    pos = 0
    for child in list(p_el):
        tag = etree.QName(child).localname
        if tag == "r":
            text = _run_text(child)
            r_start, r_end = pos, pos + len(text)
            pos = r_end
            if r_end <= start or r_start >= end or not text:
                continue
            run = child
            if r_start < start:
                run = _split_run(run, start - r_start)
                r_start = start
            if r_end > end:
                _split_run(run, end - r_start)
                run = run.getprevious()
            covered.append(run)
        elif tag == "br":
            pos += 1
        elif tag == "fld":
            pos += _fld_len(child)
    return covered


# ------------------------------------------------------------- rel plumbing


def _slide_rels_map(pkg: PptxPackage, part: str) -> dict[str, dict]:
    out: dict[str, dict] = {}
    if not pkg.has_part(rels_name(part)):
        return out
    for rel in pkg.rels_for(part).getroot():
        out[rel.get("Id")] = {
            "type": rel.get("Type"),
            "target": rel.get("Target", ""),
            "external": rel.get("TargetMode") == "External",
        }
    return out


def _external_rel(pkg: PptxPackage, part: str, url: str) -> str:
    for rid, rel in _slide_rels_map(pkg, part).items():
        if (
            rel["type"] == RT_HYPERLINK
            and rel["external"]
            and rel["target"] == url
        ):
            return rid
    return pkg.add_relationship(part, RT_HYPERLINK, url, external=True)


def _jump_rel(pkg: PptxPackage, part: str, dest_part: str) -> str:
    for rid, rel in _slide_rels_map(pkg, part).items():
        if (
            rel["type"] == RT_SLIDE
            and not rel["external"]
            and resolve_target(part, rel["target"]) == dest_part
        ):
            return rid
    target = posixpath.relpath(dest_part, posixpath.dirname(part))
    return pkg.add_relationship(part, RT_SLIDE, target.replace("\\", "/"))


def _gc_link_rels(pkg: PptxPackage, part: str, rids: set[str]) -> list[str]:
    """Drop hyperlink/jump rels from `rids` that nothing in the part
    references anymore. Only hyperlink- and slide-reltype rels are eligible
    (never layout/image/etc., whatever the caller passes)."""
    if not rids or not pkg.has_part(rels_name(part)):
        return []
    still_used: set[str] = set()
    for el in pkg.root(part).iter():
        for attr, value in el.attrib.items():
            if attr.startswith(f"{{{NSMAP['r']}}}") and value:
                still_used.add(value)
    removed: list[str] = []
    rels_root = pkg.rels_for(part).getroot()
    for rel in list(rels_root):
        rid = rel.get("Id")
        if (
            rid in rids
            and rid not in still_used
            and rel.get("Type") in (RT_HYPERLINK, RT_SLIDE)
        ):
            rels_root.remove(rel)
            removed.append(rid)
    if removed:
        pkg.mark_dirty(rels_name(part))
    return removed


# ------------------------------------------------------------ hlink surgery


def _existing_hlinks(container: etree._Element) -> list[etree._Element]:
    return [
        el
        for el in container
        if el.tag in (qn("a:hlinkClick"), qn("a:hlinkHover"))
    ]


def _make_hlink(rid: str, action: str | None, tooltip: str | None):
    el = etree.Element(qn("a:hlinkClick"))
    el.set(_R_ID, rid)
    if action:
        el.set("action", action)
    if tooltip:
        el.set("tooltip", tooltip)
    return el


def _set_cnvpr_hlink(
    cnvpr: etree._Element, rid: str, action: str | None, tooltip: str | None
) -> list[str]:
    """Replace the shape-level hlinkClick; returns the rIds of replaced
    links (for rel GC). Media playback affordances refuse."""
    replaced: list[str] = []
    for el in _existing_hlinks(cnvpr):
        if el.get("action") == _ACTION_MEDIA:
            raise UnsupportedStructure(
                "this shape is a media frame (its click action plays the "
                "video/audio); refusing to overwrite the playback control "
                "with a hyperlink"
            )
        if el.tag == qn("a:hlinkClick"):
            old = el.get(_R_ID)
            if old:
                replaced.append(old)
            cnvpr.remove(el)
    cnvpr.insert(0, _make_hlink(rid, action, tooltip))
    return replaced


def _set_run_hlink(
    run: etree._Element, rid: str, action: str | None, tooltip: str | None
) -> list[str]:
    rpr = run.find(qn("a:rPr"))
    if rpr is None:
        rpr = etree.Element(qn("a:rPr"))
        run.insert(0, rpr)  # rPr is the first child of a:r
    replaced: list[str] = []
    for el in _existing_hlinks(rpr):
        if el.tag == qn("a:hlinkClick"):
            old = el.get(_R_ID)
            if old:
                replaced.append(old)
            rpr.remove(el)
    ext = rpr.find(qn("a:extLst"))
    hl = _make_hlink(rid, action, tooltip)
    if ext is not None:
        ext.addprevious(hl)  # hlinkClick precedes extLst in CT_TextCharacterProperties
    else:
        rpr.append(hl)
    return replaced


# ------------------------------------------------------------------- public


def set_hyperlink(
    pkg: PptxPackage,
    slide,
    target,
    url: str | None = None,
    to_slide=None,
    tooltip: str | None = None,
) -> dict:
    """Set a hyperlink on a shape or a text range (replacing any link
    already there).

    target: shape id, or {"shape_id": N, "paragraph": P, "start": S,
    "end": E} for a text range (offsets in paragraph characters; omit
    start/end to link the whole paragraph). Exactly one destination:
    url (external, stored as a TargetMode="External" rel) or to_slide (a
    slide index or {"slide_id": N}; stored as the jump action plus an
    internal slide rel, the structure slide deletion knows how to neuter).
    tooltip: hover text.
    """
    if (url is None) == (to_slide is None):
        raise PptMcpError(
            "pass exactly one of url (external link) or to_slide "
            "(jump to a slide in this deck)"
        )
    rec = resolve_slide(pkg, slide)
    part = rec["part"]
    tgt = _parse_target(target)

    if url is not None:
        if not isinstance(url, str) or not url.strip():
            raise PptMcpError("url must be a non-empty string")
        url = url.strip()
        if ":" not in url:
            raise PptMcpError(
                f"url {url!r} has no scheme; pass a full URL "
                "(https://..., mailto:..., file:///...)"
            )
        action = None
        dest_info = {"url": url}
    else:
        dest = resolve_slide(pkg, to_slide)
        if dest["part"] == part:
            raise PptMcpError(
                f"to_slide resolves to the same slide (index {dest['index']});"
                " a slide cannot jump to itself"
            )
        action = _ACTION_SLIDE_JUMP
        dest_info = {
            "target_slide": {
                "index": dest["index"],
                "slide_id": dest["slide_id"],
            }
        }

    elem, _chain = _shapes._find_shape(pkg, part, tgt["shape_id"])

    # Validate everything that can refuse BEFORE any mutation.
    if not tgt["text"]:
        cnvpr = _cnvpr_of(elem)
        for existing in _existing_hlinks(cnvpr):
            if existing.get("action") == _ACTION_MEDIA:
                raise UnsupportedStructure(
                    "this shape is a media frame (its click action plays "
                    "the video/audio); refusing to overwrite the playback "
                    "control with a hyperlink"
                )
    else:
        paragraphs = _paragraphs_of(elem)
        if tgt["paragraph"] >= len(paragraphs):
            raise TargetNotFound(
                f"paragraph {tgt['paragraph']} out of range; shape "
                f"{tgt['shape_id']} has {len(paragraphs)} paragraphs"
            )
        p_el = paragraphs[tgt["paragraph"]]
        start = tgt["start"] if tgt["start"] is not None else 0
        end = tgt["end"] if tgt["end"] is not None else _paragraph_len(p_el)
        _validate_range(p_el, start, end)

    if url is not None:
        rid = _external_rel(pkg, part, url)
    else:
        rid = _jump_rel(pkg, part, dest["part"])

    replaced: list[str] = []
    runs_linked = 0
    if not tgt["text"]:
        replaced = _set_cnvpr_hlink(cnvpr, rid, action, tooltip)
        where = "shape"
    else:
        for run in _covered_runs(p_el, start, end):
            replaced.extend(_set_run_hlink(run, rid, action, tooltip))
            runs_linked += 1
        where = "text"
    pkg.mark_dirty(part)
    gc_removed = _gc_link_rels(pkg, part, set(replaced) - {rid})

    result = {
        "shape_id": tgt["shape_id"],
        "kind": "external" if url is not None else "slide",
        "where": where,
        "rid": rid,
        "tooltip": tooltip,
        "slide_index": rec["index"],
        "slide_id": rec["slide_id"],
        **dest_info,
    }
    if where == "text":
        result["runs_linked"] = runs_linked
    if gc_removed:
        result["replaced_rels_removed"] = gc_removed
    return result


def remove_hyperlink(pkg: PptxPackage, slide, target) -> dict:
    """Remove hyperlink(s) from a shape or text range. target: shape id
    (removes the shape-level link AND every run-level link in the shape) or
    {"shape_id": N, "paragraph": P[, "start": S, "end": E]} (removes links
    from the covered runs only). Orphaned hyperlink/jump rels are dropped.
    Media playback affordances are left alone."""
    rec = resolve_slide(pkg, slide)
    part = rec["part"]
    tgt = _parse_target(target)
    elem, _chain = _shapes._find_shape(pkg, part, tgt["shape_id"])

    removed_rids: set[str] = set()
    removed = 0

    def _strip(container: etree._Element) -> int:
        n = 0
        for el in _existing_hlinks(container):
            if el.get("action") == _ACTION_MEDIA:
                continue
            rid = el.get(_R_ID)
            if rid:
                removed_rids.add(rid)
            container.remove(el)
            n += 1
        return n

    if not tgt["text"]:
        removed += _strip(_cnvpr_of(elem))
        body = elem.find(qn("p:txBody"))
        if body is not None:
            for rpr in body.iter(qn("a:rPr")):
                removed += _strip(rpr)
    else:
        paragraphs = _paragraphs_of(elem)
        if tgt["paragraph"] >= len(paragraphs):
            raise TargetNotFound(
                f"paragraph {tgt['paragraph']} out of range; shape "
                f"{tgt['shape_id']} has {len(paragraphs)} paragraphs"
            )
        p_el = paragraphs[tgt["paragraph"]]
        start = tgt["start"] if tgt["start"] is not None else 0
        end = tgt["end"] if tgt["end"] is not None else _paragraph_len(p_el)
        _validate_range(p_el, start, end)
        for run in _covered_runs(p_el, start, end):
            rpr = run.find(qn("a:rPr"))
            if rpr is not None:
                removed += _strip(rpr)

    if removed:
        pkg.mark_dirty(part)
    gc_removed = _gc_link_rels(pkg, part, removed_rids)
    return {
        "shape_id": tgt["shape_id"],
        "removed": removed,
        "rels_removed": gc_removed,
        "slide_index": rec["index"],
        "slide_id": rec["slide_id"],
    }


# ------------------------------------------------------------------ listing


def _classify(
    pkg: PptxPackage,
    part: str,
    el: etree._Element,
    rels: dict[str, dict],
    slide_parts: set[str],
) -> dict | None:
    """One hlinkClick/hlinkHover element -> a report record, or None for
    non-hyperlink affordances (media controls, inert empty links)."""
    action = el.get("action") or ""
    rid = el.get(_R_ID)
    if action == _ACTION_MEDIA:
        return None
    record: dict = {
        "trigger": "hover" if el.tag == qn("a:hlinkHover") else "click",
        "tooltip": el.get("tooltip"),
        "broken": False,
    }
    if action.startswith(_ACTION_SHOW_JUMP):
        # ppaction://hlinkshowjump?jump=firstslide|lastslide|... (no rel)
        record["kind"] = "show_jump"
        record["jump"] = action.partition("jump=")[2] or action
        return record
    if not rid:
        if action == _ACTION_SLIDE_JUMP:
            # A neutered-but-not-removed jump (r:id gone): report as broken.
            record.update(kind="slide", broken=True,
                          problem="jump link has no relationship id")
            return record
        return None  # inert hlinkClick (e.g. r:id="") carries no link
    rel = rels.get(rid)
    if rel is None:
        record.update(
            kind="slide" if action == _ACTION_SLIDE_JUMP else "external",
            broken=True,
            problem=f"relationship {rid} missing from the slide rels",
        )
        return record
    if rel["external"]:
        record["kind"] = "external"
        record["url"] = rel["target"]
        if not rel["target"]:
            record.update(broken=True, problem=f"{rid} has an empty Target")
        return record
    if rel["type"] == RT_SLIDE:
        record["kind"] = "slide"
        dest = resolve_target(part, rel["target"])
        if not pkg.has_part(dest):
            record.update(
                broken=True,
                problem=f"{rid} targets missing part {dest}",
            )
        elif dest not in slide_parts:
            record.update(
                broken=True,
                problem=f"{rid} targets {dest}, which is not registered in "
                "the presentation (deleted slide?)",
            )
        else:
            record["target_part"] = dest
        return record
    record.update(
        kind="other",
        broken=True,
        problem=f"{rid} is internal with unexpected type {rel['type']}",
    )
    return record


def list_hyperlinks(pkg: PptxPackage, scope=None) -> dict:
    """Every hyperlink in scope (default: all slides): external URLs and
    jump-to-slide links, on shapes and on text runs, with broken-target
    detection (missing rels, rels to deleted/unregistered slides, empty
    URLs). Media playback controls and inert links are not hyperlinks and
    are not listed."""
    recs = slides_in_scope(pkg, scope)
    table = slide_table(pkg)
    slide_parts = {r["part"] for r in table}
    part_index = {r["part"]: r for r in table}
    out: list[dict] = []
    for rec in recs:
        part = rec["part"]
        rels = _slide_rels_map(pkg, part)
        sp_tree = pkg.root(part).find(f"{qn('p:cSld')}/{qn('p:spTree')}")
        if sp_tree is None:
            continue
        for elem, _kind, _z, _parent in iter_shapes(sp_tree):
            cnvpr = next(elem.iter(qn("p:cNvPr")), None)
            shape_id = int(cnvpr.get("id")) if cnvpr is not None else None
            shape_name = cnvpr.get("name", "") if cnvpr is not None else ""
            base = {
                "slide_index": rec["index"],
                "slide_id": rec["slide_id"],
                "shape_id": shape_id,
                "shape_name": shape_name,
            }
            if cnvpr is not None:
                for el in _existing_hlinks(cnvpr):
                    record = _classify(pkg, part, el, rels, slide_parts)
                    if record is not None:
                        out.append({**base, "where": "shape", **record})
            body = elem.find(qn("p:txBody"))
            if body is None:
                continue
            for p_idx, p_el in enumerate(body.findall(qn("a:p"))):
                for run in p_el.findall(qn("a:r")):
                    rpr = run.find(qn("a:rPr"))
                    if rpr is None:
                        continue
                    for el in _existing_hlinks(rpr):
                        record = _classify(pkg, part, el, rels, slide_parts)
                        if record is not None:
                            out.append({
                                **base,
                                "where": "text",
                                "paragraph": p_idx,
                                "text": _run_text(run),
                                **record,
                            })
    # Resolve jump targets to current indexes/ids for the report.
    for record in out:
        dest = record.pop("target_part", None)
        if dest is not None:
            dest_rec = part_index.get(dest)
            if dest_rec is not None:
                record["target_slide"] = {
                    "index": dest_rec["index"],
                    "slide_id": dest_rec["slide_id"],
                }
    broken = sum(1 for r in out if r["broken"])
    return {
        "hyperlinks": out,
        "count": len(out),
        "broken_count": broken,
        "slides_scanned": len(recs),
    }
